### ISSUE TITLE
Australian Lag Reduction Scheme

### ISSUE THREAD

**Issue by EXYZED** [AustralianBureauOfAdministration/Australia#2]
[AUSTRALIA](https://github.com/AustralianBureauOfAdministration/Australia/wiki)

# Addressing Lag in Sydney 2.0
Lag has become a prevalent issue in inhibiting the quality of game-play in Sydney, it prevents some less-able users from accessing the game and playing the game smoothly, hindering the over-all play quality of the game. This issue will outline possible actions which can be taken to reduce lag in Sydney.

# Parts and Physical Instances.
**Be aware that there have been identified duplicate parts. These parts exist in one another and are hidden by illusion. attempting to resolve this issue is difficult but this needs to be addressed and concerned for future builds**

## Physics Handling Reduction 
Any moving parts inside the game contribute to the lag of the game, this is where we need to be aware and conscious about the use of cars (they are in itself a moving body of parts).

#### For cars:

- Un-collide most of the car and leave physics based instances to be collisional (i.e. Wheels and seats).
- Limit the number of cars that a player can spawn, such that the previous car is destroyed if the player leaves the game or that it is destroyed when the player spawns a **second** car.

#### For the Workspace:

- Large buildings should be un-collided (the details of the building un-collided), then replaced by a large skeletal block which handles the collision of the building. This reduces the complexity of the physical boundaries of the block.

- Repeating parts (which re-occur in pattern) should be replaced with a texture. So far the fence towards the ADF and government house is being replaced, there were many unions there. An attempt to reduce the triangle count has been made.

  - Road lines should be replaced with a texture: A comment will follow up the model containing the textures for the road lines, road lines should not be made of parts and unions.

- Increase the thickness of the roads to ensure that the wheel of the vehicle does not clip into the underside of the baseplate.

- Ensuring that parts should be anchored when stationary. Selecting the whole game and enabling the 'anchored' property is not the appropriate way of doing this as some parts are designed to move. During testing phases briefly check corners of the game to ensure that parts haven't fallen onto the ground, use F3X ingame to highlight parts to check if any parts have fallen which are not visible to the player.

## Triangular operations
MeshParts and Unions should be kept low poly. Do not union parts if a opportunity is given, only union parts for qualitative purposes and not quantitative means (meaning that you don't union things just to reduce the part count). Refrain from using high-poly imported meshes whenever possible.

###### Some identified issues concerning this:
  - Roads have been unioned to reduce part-count, this is mildly inappropriate (ADF and Government House needs to be checked for this)
  - There are unions with one single part (meaning that no constructive geometric operation has been carried out on the union, ununion these immediately).
  - For large structural buildings, windows forming the detail of these buildings are extremely high-poly, ranging from 50k to 100k polygons, it is suggested that parts are used instead of unions for windows. Reduction has been carried out on one building and has been proven to reduce render-lag **SIGNIFICANTLY**

## General Parts
Parts should be confined to the provided ROBLOX Textures. Using custom textures on parts for detail means that the loading time of the game is increased.

Reducing parts means that the quality of the game in general may fall if not done efficiently, do not attempt to reduce the skeletal structure of a building.

- Avoid using custom textures unless appropriate. (It is usually appropriate to do so when the part is large)
- Avoid using the 'Glass' Material texture.
- Avoid layering transparent objects. Keep things opaque if possible even if it compromising shader quality.

## Building Habits
In builds, building developers should be conscious of part count and should try to reduce the part count at any given instance. For example, if parts are aligned in their project, these parts can be replaced with one large resized part which takes the span of all the previous parts. Be aware that the player may not spend too long in one particular area to notice the detail of your work. For areas which are usually free of player activity - reducing the quality of your build is beyond acceptable.

For issues concerning the alignment of parts by alignment (such that it is mathematically impossible to get two parts to perfectly align). Avoid using unions to solve this issue and use an alignment plug-in for ROBLOX Studio (this will be provided as a follow-up).

Avoid using extremely low increments. Numeric data is stored into every individual instance of the game. If possible always round a instance to the nearest appropriate increment and change the increment to then further work with the project. The Fee-Trex (F3X) Plug-in handles this well as it provides properties concerning increments. If trying to get two parts to join together is an issue, do not use small increments to do this, rather use a plug-in to connect the two faces of the parts to align.

## Community-Based Models.
The use of CBMs (also known as Free Models) is highly discouraged in the development of Sydney 2.0. Most models provided by the community can be models from an older ROBLOX time-period and is not optimised for use. (Such that they are not detailed or scripts are not compatible with new standards).
**CBMs are commonly infested with viruses, these viruses copy themselves into EVERY instance of the game and cause MAJOR lag, ensure you install a trusted plug-in which can help you with removing viruses from models. Be aware that some plug-ins are infected with viruses**.

# Scripting

- Avoid using yields or anything time-based in script threads. For example, the use of render-stepped should be avoided.

- Do not yield the script in order to make it work. i.e. some developers often put a large wait at the beginning of the script to ensure everything in workspace has loaded. This ***may*** work but is however a very inefficient method with dealing with this. Use WaitForChild() and designate a specific local function to deal with missing parts that return an error.

- Attempt to condense code if possible. Try to comment on the code to make better understanding. Code can be easily obscured when it is large.

** A lag-free environment is the objective here, a community-based support group has been created on discord for this**

##### For Filtering Enabled-Based scripts:
Attempt to handle everything client-side and designate the server-script to handle the physical operations of the client.

---
For questions contact danté#2374.
XLNS_XYZ.

This issue is open to additional comments. Please make sure comments are detailed and titled. Use markdown to your advantage.

**Comment by EXYZED** [comment]
# Useful Studio Plug-ins

Alignment issues : https://www.roblox.com/library/165534573/Stravant-ResizeAlign-Fixed
Edge Alignment : https://www.roblox.com/library/159928305/Stravant-EdgeAlign
Fee-Trex (F3X) : https://www.roblox.com/library/144950355/Building-Tools-by-F3X-Plugin
Class conversion : https://www.roblox.com/library/906681627/Quentys-Class-Converter-API-based
Curve Handling : https://www.roblox.com/library/144938633/Archimedes-Two-v2-4

**Comment by EXYZED** [comment]
Traffic Line textures : https://www.roblox.com/library/735333612/TrafficLines-V3

**Comment by AnthonyJAbbott** [comment]
Very GOOD
